services:
    zookeeper1:
        image: zookeeper:latest
        container_name: zookeeper1
        environment:
            - ZOO_SERVERS=server.1=zookeeper1:2888:3888;2181 server.2=zookeeper2:2888:3888;2181 server.3=zookeeper3:2888:3888;2181
            - ZOO_MY_ID=1
        ports:
            - 2181:2181

    zookeeper2:
        image: zookeeper:latest
        container_name: zookeeper2
        environment:
            - ZOO_SERVERS=server.1=zookeeper1:2888:3888;2181 server.2=zookeeper2:2888:3888;2181 server.3=zookeeper3:2888:3888;2181
            - ZOO_MY_ID=2
        ports:
            - 2182:2181

    zookeeper3:
        image: zookeeper:latest
        container_name: zookeeper3
        environment:
            - ZOO_SERVERS=server.1=zookeeper1:2888:3888;2181 server.2=zookeeper2:2888:3888;2181 server.3=zookeeper3:2888:3888;2181
            - ZOO_MY_ID=3
        ports:
            - 2183:2181

    kafka1:
        image: wurstmeister/kafka
        container_name: kafka1
        environment:
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
            - KAFKA_ADVERTISED_HOST_NAME=kafka1
            - KAFKA_BROKER_ID=1
        ports:
            - 9092
        depends_on:
            - zookeeper1
            - zookeeper2
            - zookeeper3

    kafka2:
        image: wurstmeister/kafka
        container_name: kafka2
        environment:
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
            - KAFKA_ADVERTISED_HOST_NAME=kafka2
            - KAFKA_BROKER_ID=2
        ports:
            - 9092
        depends_on:
            - zookeeper1
            - zookeeper2
            - zookeeper3

    kafka3:
        image: wurstmeister/kafka
        container_name: kafka3
        environment:
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
            - KAFKA_ADVERTISED_HOST_NAME=kafka3
            - KAFKA_BROKER_ID=3
        ports:
            - 9092
        depends_on:
            - zookeeper1
            - zookeeper2
            - zookeeper3
